[package]
name = "gif-jni"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gif = "0.11.3"
jni = "0.19.0"
skia-bindings = "0.49.0"
skia-safe = "0.49.0"

[lib]
crate-type = ["cdylib"]
